spring:
  application:
    name: jiangdaxian-gateway-zuul_test_4
  profiles: dev
  context-path: test4
server:
  port: 3254
eureka:
  instance:
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      default-zone: http://dis1:8761/eureka/,http://dis2:8761/eureka/,http://dis3:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
