spring:
  application:
    name: jiangdaxian-gateway-zuul_test
  profiles: dev
server:
  port: 8250
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://discovery1:8761/eureka/,http://discovery2:8762/eureka/, http://discovery3:8763/eureka/
    fetch-registry: true
    register-with-eureka: true
