spring:
  application:
    name: jiangdaxian-gateway-zuul_test_5
  profiles: dev
server:
  port: 3255
  context-path: /test5
eureka:
  instance:
    appname: jiangdaxian-gateway-zuul_test_5
    prefer-ip-address: false
    hostname: ${hostname}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://dis1:8761/eureka/,http://dis2:8761/eureka/,http://dis3:8761/eureka/
